### ISSUE TITLE
When is the next release planned?

### ISSUE THREAD

**Issue by srikanth-nettem** [saymedia/terraform-s3-dir#10]
I am waiting for the release of the latest commit that handles css mime-type? My static website is looking crazy for the same reason.

**Comment by srikanth-nettem** [comment]
Is this project active? There hasn't been any response since a week.

**Comment by srikanth-nettem** [comment]
@apparentlymart can you release the latest commits?

**Comment by apparentlymart** [comment]
Hi @srikanth-nettem!

I released v0.0.4 today. This codebase is generally considered "done" by the team that built it and so there are no current active maintainers for the project, and so this will probably be the last release for the foreseeable future.
